# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


from Tests.configs import Logar

class TestConcluiraula():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_concluiraula(self):
    driver = Logar(self.driver)
    driver.find_element(By.CSS_SELECTOR, ".btn-header:nth-child(3) > .btn").click()

    WebDriverWait(driver, 10).until(
      EC.url_contains("dash")
    )

    self.driver.find_element(By.CSS_SELECTOR, ".card-link:nth-child(1) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-card").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aula-curso-item:nth-child(2) .title-font-sec").click()
    self.driver.find_element(By.CSS_SELECTOR, ".undefined:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".concluida").is_displayed
    
  
