# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestBloqueiarrotassemauth():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bloqueioauth(self):
    self.driver.get("https://extensao-first-step.vercel.app/")
    self.driver.set_window_size(897, 656)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-header:nth-child(2) > .btn").click()
    
    WebDriverWait(self.driver, 10).until(
        EC.url_contains("login")
    )

    assert "login" in self.driver.current_url
  
